#!/bin/bash

#####
#
# Builder
# 
# Docker based cross compilation tool
#
#####


## start utils

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
white=`tput setaf 7`
reset=`tput sgr0`

error()
{
  # was an error passed to this function?
  if [ -z "$1" ]; then
    #if not, print a standard error
    echo "[${red}DEBUG ${yellow}@ ${green}$(date +"%T")${reset}] ${red}Error occurred!${reset}"
  else
    # if so, we can print the message in an error
    echo "[${red}DEBUG ${yellow}@ ${green}$(date +"%T")${reset}] ${red}$@${reset}"
  fi
  exit 1
}

# log function
function log {
  echo "[${cyan}INFO  ${yellow}@ ${green}$(date +"%T")${reset}] $@"
}

# marker function
function marker {
  log "${yellow}===== ${blue}$@ ${yellow}=====${reset}"
}

## end utils

IMAGE="${USER}/$2"
TAG="v1"

FUNCTION="$1"
if [ "$3" == "--no-cache" ]; then
	NO_CACHE="--no-cache"
	shift 1;
fi
shift 2;
BOB_ARGUMENTS=($@)

if [ -f "$(pwd)/.bobenv" ]; then
	ENV="--env-file $(pwd)/.bobenv"
elif [ -f "${HOME}/.bobenv" ]; then
	ENV="--env-file ${HOME}/.bobenv"
else
	log "Environment file not found!"
	ENV=(	--env PATH="/opt/arm-toolchain/linaro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
		--env ARCH="arm" \
		--env CROSS_COMPILE="arm-linux-gnueabihf-"
	)
		
fi

# creates a container based on an input directory and image name
function container_build {
	log "Building image: ${IMAGE}:${TAG}"
	if [ -f "${BOB_ARGUMENTS[0]}" ]; then
		echo "${BOB_ARGUMENTS[0]} is a file"
		BOB_ARGUMENTS="-f ${BOB_ARGUMENTS[0]} $(dirname ${BOB_ARGUMENTS[0]})"
	elif [ -d "${BOB_ARGUMENTS[0]}" ]; then
		BOB_ARGUMENTS="${BOB_ARGUMENTS[0]}"
	else
		echo "${BOB_ARGUMENTS[0]} is not a file or directory"
		echo "exiting now."
		exit 1
	fi
	docker build ${NO_CACHE} -t "${IMAGE}:${TAG}" ${BOB_ARGUMENTS}
	
}

# launches a docker container.
# if extra commands are specified it launches them, otherwise it starts up bash
function container_launch {
	if [ "${BOB_ARGUMENTS[0]}" == "-d" ]; then
		FOLDER="${BOB_ARGUMENTS[1]}"
		WORKDIR=""
		if [[ "$FOLDER" != /* ]]; then
			WORKDIR="${FOLDER}"
			FOLDER="$(pwd)"
		fi
		BOB_ARGUMENTS=(${BOB_ARGUMENTS[*]:2})
		echo "Using folder $FOLDER"
	else
		FOLDER="$(pwd)"
		echo "Using folder $FOLDER"
	fi

	VOLUME="${FOLDER}"
	VOLUME_MOUNTPOINT="/tmp/bob/${FOLDER##*/}"
	VOLUME_WORKDIR="${VOLUME_MOUNTPOINT}/${WORKDIR}"
	# FOLDER="${BOB_ARGUMENTS[0]}"
	log "Launching in ${FOLDER}"
	log "Mount ${VOLUME_MOUNTPOINT}"
	# BOB_ARGUMENTS=(${BOB_ARGUMENTS[*]:1})
	log "Args: ${BOB_ARGUMENTS}"
	if [ -n "${BOB_ARGUMENTS}" ]; then
		A_VOLUME="${VOLUME}:${VOLUME_MOUNTPOINT}"
		A_WORKDIR="${VOLUME_WORKDIR}"
		# log "Running in folder: ${A_WORKDIR}"
		shift
		# log "Running image: ${IMAGE}:${TAG}"
		# log "Arguments: ${BOB_ARGUMENTS[*]}"
		# log "Environment: ${ENV[*]}"
		# log "Volume: ${VOLUME}"
		marker "${IMAGE}"
		docker run -t -i \
			${ENV[*]} \
			--workdir="${A_WORKDIR}" \
			--volume="${A_VOLUME}" \
			"${IMAGE}:${TAG}" \
			${BOB_ARGUMENTS[*]}
	else
		docker run -t -i \
			${ENV[*]} \
			--workdir="${A_WORKDIR}" \
			--volume="${VOLUME}:${VOLUME_MOUNTPOINT}" \
			"${IMAGE}:${TAG}"
	fi
}
#			\ # --user=${USER}:${USER} \

case "$FUNCTION" in
	create) container_build
		;;
	run) container_launch
		;;
	*)	echo "Unrecognized option: ${FUNCTION}"
		;;
esac
